Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,8 +1,8 @@
 # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
 # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
 env:
-  COVERAGE_THRESHOLD: 2
-  CODE_SMELLS_THRESHOLD: 2
+  COVERAGE_THRESHOLD: 200
+  CODE_SMELLS_THRESHOLD: 20
   VULNERABILITIES_THRESHOLD: 2
 name: Maven 
 
@@ -98,6 +98,20 @@ jobs:
                     exit 1
                   else
                     echo "Expected ${metric%.*} - ${{env.COVERAGE_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
+                  
+            elif [ "$metric" == "code_smells" ] ;
+              then
+                if [ "${value%.*}" -gt ${{env.CODE_SMELLS_THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
                     echo "Actual ${metric%.*} - ${value%.*}"
                     echo "Sonar code coverage Gate: Passed"
                   fi
